spring:
  profiles:
    active: ipex
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.proc.param_null_passing : true
    open-in-view: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  mvc:
    throw-exception-if-no-handler-found : true

scheduler:
  common:
    enable : false
    fixedRate:
      in:
        milliseconds: 10000
  telegram:
    enable : false
    fixedRate:
      in:
        milliseconds: 10000
  rolehandler:
    enable : false
    fixedRate:
      in:
        milliseconds: 10000
  justin:
    enable: false
    fixedRate:
      in:
        milliseconds: 3600000
  ukrpost:
    enable: true
    fixedRate:
      in:
        milliseconds: 7200000

post:
  request:
    declaration:
      create:
        enable: true
    dispatch:
      create:
        enable: true

server :
  compression :
    enabled : true
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /hydracargo2
    session:
      timeout: 3600

---

spring:
  profiles: vex_test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dataSourceClassName : oracle.jdbc.pool.OracleDataSource
#    driver-class-name : oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@//localhost:1523/ORCLPDB1
    username : HCARGO
    password : qazzaq
    url : jdbc:oracle:thin:@//localhost:1523/ORCLPDB1
    hikari:
      connection-init-sql: alter session set current_schema=HCARGO
      minimum-idle: 2
      maximum-pool-size: 5
      schema: HCARGO

server :
  port : 8081

telegram :
  BOT_CREATOR_ID : 363275968
  bot_start : true
  BOT_TOKEN : 606957316:AAH1ySWFd1gGTCh4DBzITIG3qJbobOjCJ3Y
  BOT_USERNAME : eeExpress_TestBot
  INFO: ee.express.info

scheduler:
  justin:
    enable: false
    fixedRate:
      in:
        milliseconds: 3600000

---

spring:
  profiles: vex
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dataSourceClassName : oracle.jdbc.pool.OracleDataSource
    url: jdbc:oracle:thin:@//localhost/ORCLPDB1
    username : HCARGO
    password : qazzaq
    hikari:
      connection-init-sql: alter session set current_schema=HCARGO
      minimum-idle: 2
      maximum-pool-size: 10
      schema: HCARGO

server :
  port : 8080

telegram :
  BOT_CREATOR_ID : 363275968
  bot_start : true
  BOT_TOKEN : 575427048:AAHmoE-Ad9MvT0AKgcOyKtI0g2EP1VPb3Rk
  BOT_USERNAME : eeExpressBot
  INFO: ee.express.info

---

  spring:
    profiles: ipex
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      dataSourceClassName: oracle.jdbc.pool.OracleDataSource
      url: jdbc:oracle:thin:@//localhost/ORCLPDB1
      username: HCARGO
      password: qazzaq
      hikari:
        connection-init-sql: alter session set current_schema=HCARGO
        minimum-idle: 2
        maximum-pool-size: 10
        schema: HCARGO

  server:
    port: 8080

  telegram:
    BOT_CREATOR_ID: 363275968
    bot_start: true
    BOT_TOKEN: 920706355:AAFMvUe1IaAn4mrJUf0MOv1DPgnNswXyHcU
    BOT_USERNAME: ipex_delivery_bot
    INFO: ipex.info

---

    spring:
      profiles: ipex_test
      datasource:
        type: com.zaxxer.hikari.HikariDataSource
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        url: jdbc:oracle:thin:@//localhost:1526/ORCLPDB1
        username: HCARGO
        password: qazzaq
        hikari:
          connection-init-sql: alter session set current_schema=HCARGO
          minimum-idle: 2
          maximum-pool-size: 10
          schema: HCARGO

    server:
      port: 8081

    telegram:
      BOT_CREATOR_ID: 363275968
      bot_start: true
      BOT_TOKEN: 1020814764:AAE-WSMn-g1lJuHWVEApQ53wS5bb2w3a0xw
      BOT_USERNAME: ipex_delivery_test_bot
      INFO: ipex.info

---

      spring:
        profiles: giba_test
        datasource:
          type: com.zaxxer.hikari.HikariDataSource
          dataSourceClassName: oracle.jdbc.pool.OracleDataSource
          url: jdbc:oracle:thin:@//localhost:1530/ORCLPDB1
          username: HCARGO
          password: qazzaq
          hikari:
            connection-init-sql: alter session set current_schema=HCARGO
            minimum-idle: 2
            maximum-pool-size: 10
            schema: HCARGO

      server:
        port: 8081

      telegram:
        BOT_CREATOR_ID: 363275968
        bot_start: true
        BOT_TOKEN: 1089235418:AAGaTGDmBcl5a9ikbMKcP05_k_0XOE0jFVg
        BOT_USERNAME: gibalogisticbot
        INFO: giba.info

      post:
        request:
          declaration:
            create:
              enable: false
          dispatch:
            create:
              enable: false

---

        spring:
          profiles: giba
          datasource:
            type: com.zaxxer.hikari.HikariDataSource
            dataSourceClassName: oracle.jdbc.pool.OracleDataSource
            url: jdbc:oracle:thin:@//localhost/ORCLPDB1
            username: HCARGO
            password: qazzaq
            hikari:
              connection-init-sql: alter session set current_schema=HCARGO
              minimum-idle: 2
              maximum-pool-size: 10
              schema: HCARGO

        server:
          port: 8080
          servlet:
            context-path: /giba

        telegram:
          BOT_CREATOR_ID: 363275968
          bot_start: true
          BOT_TOKEN: 958005997:AAFYcIOpFPOH28RCtcjpSB7k-zE3rwWfbHc
          BOT_USERNAME: g8user_bot
          INFO: giba.info

        post:
          request:
            declaration:
              create:
                enable: false
            dispatch:
              create:
                enable: false
